### PR TITLE
fix: add .nvmrc files since projects don't support Node 10

### PR DESCRIPTION
**Pull request by danwdart**

### CODE REVIEW

**Comment by jimlambie** [comment]
I don't think we need add these to the repo. I'm not sure how many people are using nvm - I'd be inclined to say add them to .gitignore and don't worry about committing them.

**Comment by danwdart** [comment]
Maybe upgrading to support Node 10 would be sensible now that it's in active

**Comment by eduardoboucas** [comment]
Which projects don't support Node 10?

**Comment by danwdart** [comment]
As far as I'm aware, definitely Publish but maybe the rest don't properly install because of a dependency that won't install in Node 10.

**Pull request closed without merging**
