### PR TITLE
Fix for profile image save

### PR DESCRIPTION
**Pull request by danwdart**
Fixes https://github.com/dadi/publish/issues/367

### CODE REVIEW

**Comment by jimlambie** [comment]
Shouldn't profile image be a reference to the mediaStore collection, rather than adding media fields to the images collection?

@eduardoboucas thoughts?

**Comment by danwdart** [comment]
Is that the right way to do this? Why do we need more than one table for this? I may have not been explained this one, and may have picked a bad one to start off with,

**Comment by eduardoboucas** [comment]
I'm not familiar with this implementation, but it looks like we're using a regular collection and not taking advantage of the media capabilities of API (e.g. upload). Am I right to assume that uploads are being done separately and this collection is updated with values that reference the uploaded files in the filesystem?

If that's the way we want to do it, then the PR looks fine. If we want to use the media capabilities of API ([see docs](https://docs.dadi.cloud/api/4.0#working-with-files)), then @jimlambie's suggestion is the way to go.

**Comment by danwdart** [comment]
I'm unsure what we want to do - could we agree the right way to do it, and either I can update or pass along? Sounds like that if there's a specific thing to do then I should use it?

**Comment by eduardoboucas** [comment]
I don’t want to weigh in too much because I was not involved in the build, so perhaps there was a reason for not using the media endpoints that I’m not aware of. 

@jimlambie what do you think?

**Comment by danwdart** [comment]
I think this is dealt with with the other fix

**Comment by jimlambie** [comment]
Requires API 4+

**Pull request closed without merging**
